import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { Shipment } from "./types";

function currencySymbol(code?: string) {
  const map: Record<string, string> = {
    USD: "$",
    EUR: "€",
    GBP: "£",
    XAF: "Fr",
    CAD: "$",
  };
  const c = (code || "USD").toUpperCase();
  return map[c] || c;
}

function line(text?: string | number | null) {
  if (text == null || text === "") return "N/A";
  return String(text);
}

export async function generateReceiptPdfBuffer(shipment: Shipment): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]); // LETTER
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const primary = rgb(0.145, 0.388, 0.922); // #2563EB
  const black = rgb(0.06, 0.09, 0.16);
  const muted = rgb(0.39, 0.45, 0.55);
  const lightBlue = rgb(0.94, 0.96, 1);

  const currency = currencySymbol(
    shipment.cost?.currency || shipment.package?.currency || "USD"
  );

  // Header bar
  page.drawRectangle({ x: 0, y: 692, width: 612, height: 100, color: primary });
  page.drawText("CargoWatch", {
    x: 50,
    y: 745,
    size: 26,
    font: fontBold,
    color: rgb(1, 1, 1),
  });
  page.drawText("SHIPMENT RECEIPT", {
    x: 380,
    y: 748,
    size: 12,
    font,
    color: rgb(1, 1, 1),
  });

  let y = 650;

  // Tracking box
  page.drawRectangle({
    x: 50,
    y: y - 20,
    width: 512,
    height: 50,
    color: lightBlue,
    borderColor: primary,
    borderWidth: 1.5,
  });
  page.drawText("Tracking Number", { x: 65, y: y + 10, size: 10, font, color: primary });
  page.drawText(shipment.trackingId, {
    x: 65,
    y: y - 8,
    size: 18,
    font: fontBold,
    color: black,
  });

  y -= 60;
  page.drawText("Shipment Information", { x: 50, y, size: 13, font: fontBold, color: primary });
  y -= 20;
  page.drawText(`Status: ${line(shipment.status).replaceAll("_", " ").toUpperCase()}`, {
    x: 50,
    y,
    size: 10,
    font,
    color: black,
  });
  y -= 16;
  page.drawText(
    `Created: ${shipment.createdAt ? new Date(shipment.createdAt).toLocaleString() : "N/A"}`,
    { x: 50, y, size: 10, font, color: black }
  );
  y -= 16;
  page.drawText(
    `Estimated delivery: ${
      shipment.estimatedDelivery
        ? new Date(shipment.estimatedDelivery).toLocaleString()
        : "N/A"
    }`,
    { x: 50, y, size: 10, font, color: black }
  );

  y -= 30;
  page.drawText("Sender", { x: 50, y, size: 12, font: fontBold, color: primary });
  page.drawText("Recipient", { x: 320, y, size: 12, font: fontBold, color: primary });
  y -= 18;

  const senderLines = [
    line(shipment.sender?.name),
    line(shipment.sender?.email),
    line(shipment.sender?.phone),
    [shipment.sender?.address?.street, shipment.sender?.address?.city, shipment.sender?.address?.country]
      .filter(Boolean)
      .join(", ") || "N/A",
  ];
  const recipientLines = [
    line(shipment.recipient?.name),
    line(shipment.recipient?.email),
    line(shipment.recipient?.phone),
    [
      shipment.recipient?.address?.street,
      shipment.recipient?.address?.city,
      shipment.recipient?.address?.country,
    ]
      .filter(Boolean)
      .join(", ") || "N/A",
  ];

  for (let i = 0; i < 4; i++) {
    page.drawText(senderLines[i].slice(0, 40), { x: 50, y: y - i * 14, size: 9, font, color: black });
    page.drawText(recipientLines[i].slice(0, 40), {
      x: 320,
      y: y - i * 14,
      size: 9,
      font,
      color: black,
    });
  }

  y -= 80;
  page.drawText("Package", { x: 50, y, size: 12, font: fontBold, color: primary });
  y -= 18;
  page.drawText(`Type: ${line(shipment.package?.type)}`, { x: 50, y, size: 10, font, color: black });
  y -= 14;
  page.drawText(`Weight: ${line(shipment.package?.weight)} kg`, {
    x: 50,
    y,
    size: 10,
    font,
    color: black,
  });
  y -= 14;
  page.drawText(`Description: ${line(shipment.package?.description).slice(0, 80)}`, {
    x: 50,
    y,
    size: 10,
    font,
    color: black,
  });

  y -= 28;
  page.drawText("Costs", { x: 50, y, size: 12, font: fontBold, color: primary });
  y -= 18;
  page.drawText(`Base: ${currency}${shipment.cost?.base ?? 0}`, {
    x: 50,
    y,
    size: 10,
    font,
    color: black,
  });
  y -= 14;
  page.drawText(`Shipping: ${currency}${shipment.cost?.shipping ?? 0}`, {
    x: 50,
    y,
    size: 10,
    font,
    color: black,
  });
  y -= 14;
  page.drawText(`Insurance: ${currency}${shipment.cost?.insurance ?? 0}`, {
    x: 50,
    y,
    size: 10,
    font,
    color: black,
  });
  y -= 16;
  page.drawText(`Total: ${currency}${shipment.cost?.total ?? 0}`, {
    x: 50,
    y,
    size: 11,
    font: fontBold,
    color: black,
  });

  page.drawText("This is an official receipt generated by CargoWatch.", {
    x: 50,
    y: 50,
    size: 9,
    font,
    color: muted,
  });

  const bytes = await pdfDoc.save();
  return Buffer.from(bytes);
}
