import PDFDocument from "pdfkit";
import type { Shipment } from "./types";

function currencySymbol(code?: string) {
  const map: Record<string, string> = {
    USD: "$",
    EUR: "€",
    GBP: "£",
    XAF: "Fr",
    CAD: "$",
  };
  const c = (code || "USD").toUpperCase();
  return map[c] || c;
}

export async function generateReceiptPdfBuffer(shipment: Shipment): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "LETTER" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const primary = "#2563EB";
    const currency = currencySymbol(
      shipment.cost?.currency || shipment.package?.currency || "USD"
    );

    // Header
    doc.rect(0, 0, doc.page.width, 100).fill(primary);
    doc.fillColor("#ffffff").fontSize(28).font("Helvetica-Bold").text("CargoWatch", 50, 35);
    doc.fontSize(12).font("Helvetica").text("SHIPMENT RECEIPT", doc.page.width - 220, 45, {
      width: 170,
      align: "right",
    });

    doc.fillColor("#000000");
    let y = 130;

    // Tracking box
    doc.roundedRect(50, y, doc.page.width - 100, 55, 8).fillAndStroke("#EFF6FF", primary);
    doc.fillColor(primary).fontSize(11).font("Helvetica").text("Tracking Number", 70, y + 10);
    doc
      .fillColor("#0f172a")
      .fontSize(20)
      .font("Helvetica-Bold")
      .text(shipment.trackingId, 70, y + 28);
    y += 80;

    doc.fillColor(primary).fontSize(14).font("Helvetica-Bold").text("Shipment Information", 50, y);
    y += 24;
    doc
      .fillColor("#0f172a")
      .fontSize(11)
      .font("Helvetica")
      .text(`Status: ${(shipment.status || "pending").replaceAll("_", " ").toUpperCase()}`, 50, y);
    y += 18;
    doc.text(`Created: ${shipment.createdAt ? new Date(shipment.createdAt).toLocaleString() : "N/A"}`, 50, y);
    y += 18;
    doc.text(
      `Estimated delivery: ${
        shipment.estimatedDelivery ? new Date(shipment.estimatedDelivery).toLocaleString() : "N/A"
      }`,
      50,
      y
    );
    y += 30;

    // Sender / Recipient
    const colW = (doc.page.width - 120) / 2;
    doc.fillColor(primary).fontSize(13).font("Helvetica-Bold").text("Sender", 50, y);
    doc.text("Recipient", 50 + colW + 20, y);
    y += 18;
    doc.fillColor("#0f172a").fontSize(10).font("Helvetica");
    const senderBlock = [
      shipment.sender?.name || "N/A",
      shipment.sender?.email || "",
      shipment.sender?.phone || "",
      [shipment.sender?.address?.street, shipment.sender?.address?.city, shipment.sender?.address?.country]
        .filter(Boolean)
        .join(", "),
    ]
      .filter(Boolean)
      .join("\n");
    const recipientBlock = [
      shipment.recipient?.name || "N/A",
      shipment.recipient?.email || "",
      shipment.recipient?.phone || "",
      [
        shipment.recipient?.address?.street,
        shipment.recipient?.address?.city,
        shipment.recipient?.address?.country,
      ]
        .filter(Boolean)
        .join(", "),
    ]
      .filter(Boolean)
      .join("\n");

    doc.text(senderBlock, 50, y, { width: colW });
    doc.text(recipientBlock, 50 + colW + 20, y, { width: colW });
    y += 90;

    doc.fillColor(primary).fontSize(13).font("Helvetica-Bold").text("Package", 50, y);
    y += 18;
    doc.fillColor("#0f172a").fontSize(10).font("Helvetica");
    doc.text(`Type: ${shipment.package?.type || "N/A"}`, 50, y);
    y += 14;
    doc.text(`Weight: ${shipment.package?.weight ?? "N/A"} kg`, 50, y);
    y += 14;
    doc.text(`Description: ${shipment.package?.description || "N/A"}`, 50, y, {
      width: doc.page.width - 100,
    });
    y += 30;

    doc.fillColor(primary).fontSize(13).font("Helvetica-Bold").text("Costs", 50, y);
    y += 18;
    doc.fillColor("#0f172a").fontSize(10).font("Helvetica");
    doc.text(`Base: ${currency}${shipment.cost?.base ?? 0}`, 50, y);
    y += 14;
    doc.text(`Shipping: ${currency}${shipment.cost?.shipping ?? 0}`, 50, y);
    y += 14;
    doc.text(`Insurance: ${currency}${shipment.cost?.insurance ?? 0}`, 50, y);
    y += 14;
    doc.font("Helvetica-Bold").text(`Total: ${currency}${shipment.cost?.total ?? 0}`, 50, y);

    y += 40;
    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#64748b")
      .text("This is an official receipt generated by CargoWatch.", 50, y, {
        width: doc.page.width - 100,
        align: "center",
      });

    doc.end();
  });
}
